# Generated by Django 3.1.5 on 2021-01-29 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30)),
                ('username', models.CharField(default='None', max_length=30, unique=True)),
                ('password', models.CharField(default='None', max_length=30)),
                ('emailid', models.CharField(default='None', max_length=30)),
                ('pojession', models.CharField(default='None', max_length=30)),
                ('image', models.ImageField(default='default.JPG', upload_to='')),
                ('discription', models.CharField(default='Discription about the employee here', max_length=1000)),
                ('first_name', models.CharField(default='add first name', max_length=30)),
                ('last_name', models.CharField(default='no last name', max_length=30)),
                ('middle_name', models.CharField(default='no middle name', max_length=30)),
                ('phone', models.IntegerField(default='0000000000', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='None', max_length=30, unique=True)),
                ('projedct_start_time', models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 10, 16, 592078))),
                ('project_end_time', models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 10, 16, 592078))),
                ('project_status', models.CharField(choices=[('Not assigned', 'Not assigned'), ('Close', 'Close'), ('IN PROGRESS', 'IN PROGRESS'), ('Open', 'Open'), ('In Hold', 'In Hold'), ('Testing', 'Testing')], default='Not assigned', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='None', max_length=100)),
                ('employee_name', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
