# Generated by Django 3.1.5 on 2021-01-29 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='company_email',
            field=models.EmailField(default='email@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 31, 35, 412139)),
        ),
        migrations.AddField(
            model_name='employees',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 31, 35, 412139)),
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(default='email', max_length=30),
        ),
        migrations.AddField(
            model_name='employees',
            name='enrollment_id',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('MAle', 'MALE'), ('FEMALE', 'FEMALE'), ('GAY', 'GAY')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employees',
            name='merita_state',
            field=models.CharField(choices=[('UNMARRIED', 'UNMARRIED'), ('MARRIED', 'MARRIED')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 31, 35, 412139)),
        ),
        migrations.AlterField(
            model_name='project',
            name='projedct_start_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 31, 35, 412139)),
        ),
    ]
