# Generated by Django 3.1.5 on 2021-01-29 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0003_auto_20210130_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 39, 4, 758311)),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 39, 4, 758311)),
        ),
        migrations.AlterField(
            model_name='employees',
            name='merita_state',
            field=models.CharField(choices=[('UNMARRIED', 'UNMARRIED'), ('MARRIED', 'MARRIED')], default='UNMARRIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 39, 4, 758311)),
        ),
        migrations.AlterField(
            model_name='project',
            name='projedct_start_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 2, 39, 4, 758311)),
        ),
    ]
