# Generated by Django 3.1.5 on 2021-01-30 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0005_auto_20210130_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='tipe_of_employee',
            field=models.CharField(choices=[('FULL TIME', 'FULL TIME'), ('PARTTIME', 'PARTTIME'), ('TRAINEE', 'TRAINEE')], default='TRAINEE', max_length=30),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 1, 41, 682000)),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 1, 41, 682000)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 1, 41, 688038)),
        ),
        migrations.AlterField(
            model_name='project',
            name='projedct_start_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 1, 41, 688038)),
        ),
    ]
