# Generated by Django 3.1.5 on 2021-01-30 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0006_auto_20210130_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='reportingto',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 7, 31, 660008)),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 7, 31, 660008)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 7, 31, 661004)),
        ),
        migrations.AlterField(
            model_name='project',
            name='projedct_start_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 7, 31, 661004)),
        ),
    ]
