# Generated by Django 3.1.5 on 2021-01-30 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_assignment', '0007_auto_20210130_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='project_assignment.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 59, 48, 29467)),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 59, 48, 30464)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 59, 48, 31460)),
        ),
        migrations.AlterField(
            model_name='project',
            name='projedct_start_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 30, 16, 59, 48, 31460)),
        ),
    ]
